name: test_coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: "Tests + coverage"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20']
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Go build (source)
        run: make

      - name: Go build (tests)
        run: |
          make test-container KEEP_TEST_CONTAINER=1
          podman cp go-test-container:/app/coverage.out .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out
          flags: go-${{ matrix.go-version }}
          name: coverage-go-${{ matrix.go-version }}
          fail_ci_if_error: true
          verbose: true
